name: Bump version

on:
  push:
    branches:
      - master
    paths-ignore:
      - "package.json"
      - "CHANGELOG.md"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN_ACTION }}
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: "add,Adds,new"
          major-wording: "MAJOR,cut-major"
          patch-wording:
            "patch,fixes" # Providing patch-wording will override commits
            # defaulting to a patch bump.
          rc-wording: "RELEASE,alpha"
      # - name: Bump version and push tag
      #   uses: TriPSs/conventional-changelog-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN_ACTION }}
      #     git-message: "chore(release): {version}"
      #     preset: "angular"
      #     tag-prefix: ""
      #     output-file: "CHANGELOG.md"
      #     git-user-name: ziponia
      #     git-user-email: thtjwls@gmail.com
