name: Bump version

on:
  push:
    branches:
      - master
    paths-ignore:
      - "package.json"
      - "CHANGELOG.md"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name ziponia
          git config user.email thtjwls@gmail.com
          git config pull.rebase true
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: "minor"
          major-wording: "major"
          patch-wording: "patch,fixes,fixed"
          rc-wording: "RELEASE,alpha"
