name: Bump version

on:
  push:
    branches:
      - master
    paths-ignore:
      - "package.json"
      - "CHANGELOG.md"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: git config
        run: |
          git config user.name ziponia
          git config user.email thtjwls@gmail.com

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          git-message: "{version}"
          git-user-name: "ziponia"
          git-user-email: "thtjwls@gmail.com"
          preset: "angular"
          tag-prefix: "v"
          output-file: "CHANGELOG.md"
          release-count: "10"
          skip-on-empty: "false"
          skip-version-file: "false"
          skip-commit: "false"
